export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INVALID_SESSION = 'AUTH_INVALID_SESSION';

export const AUTH_ROLE = "AUTH_ROLE";
export const USER_INFO_FETCH_START = 'USER_INFO_FETCH_START';
export const USER_INFO_FETCH_SUCCESS = 'USER_INFO_FETCH_SUCCESS';
export const USER_INFO_FETCH_FAILURE = 'USER_INFO_FETCH_FAILURE';
export const SAVE_SOLUTION_PERMISSIONS = 'SAVE_SOLUTION_PERMISSIONS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_PAGE_HEADER_TITLE = 'SET_PAGE_HEADER_TITLE';

export const SHOW_SETUP_ORG = 'SHOW_SETUP_ORG';
export const HIDE_SETUP_ORG = 'HIDE_SETUP_ORG';

export const SHOW_ORG_ALERTS = 'SHOW_ORG_ALERTS';
export const HIDE_ORG_ALERTS = 'HIDE_ORG_ALERTS';


export const STATES_FETCH_START = 'STATES_FETCH_START';
export const STATES_FETCH_SUCCESS = 'STATES_FETCH_SUCCESS';
export const STATES_FETCH_FAILURE = 'STATES_FETCH_FAILURE';


